name: Create APIView

on:
  workflow_run:
    workflows: ["Generate APIView Artifact"]
    types:
      - completed

jobs:
  create-apiview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.outputs.PullRequestRef }}
        fetch-depth: 0

    - name: Download Swagger APIView Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.APIViewArtifactsName }}
        path: ${{ github.workspace }}/artifacts/${{ github.event.workflow_run.outputs.APIViewArtifactsDirectoryName }}

    - name: Create Swagger APIView
      shell: pwsh
      run: |
        eng/scripts/Create-Swagger-APIView.ps1 `
          -ArtiFactsStagingDirectory ${{ github.workspace }}/artifacts `
          -APIViewArtifactsDirectoryName ${{ github.event.workflow_run.outputs.APIViewArtifactsDirectoryName }} `
          -APIViewArtifactsName ${{ github.event.workflow_run.outputs.APIViewArtifactsName }} `
          -APIViewUri ${{ github.event.workflow_run.outputs.APIViewAPIUri }} `
          -BuildId ${{ github.run_id }} `
          -RepoName ${{ github.repository }} `
          -PullRequestNumber ${{ github.event.workflow_run.outputs.PullRequestNumber }} `
          -Language 'Swagger' `
          -CommitSha ${{ github.sha }}
